[package]
name = "fungible_token"
version = "1.0.0"
authors = []

[addresses]
fungible_token =  "6fc937eba60ea78c23b783692aa53c89ff7f760c3dae23c40b1deac92b48017f"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
