[package]
name = "non_fungible_token"
version = "1.0.0"
authors = []

[addresses]
non_fungible_token = "e5124e2445745fd58762f4c6e49e706f0d155f0e13e43fb268ce72f00703bf07"




[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
