[package]
name = "hello_blockchain"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain_addr='c9acc39e3fa989634351b39751d4bf4a6ead0b4fc746f0c1f838ae096a30a741'


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
