[package]
name = "basic_math"
version = "1.0.0"
authors = []

[addresses]
basic_math = "882f50342c46e35c40a296bb761bc30987471938713e819769b460bf98a08924"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
