name: Build Todolist Boilerplate Template Frontend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    defaults:
      run:
        working-directory: ./templates/todolist-boilerplate/frontend
    steps:
      - uses: actions/checkout@v3

      # Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
          run_install: false

      # Install deps and build.
      - run: pnpm install
      - run: CI= pnpm build
